# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculates ScaleMat and DistMat matrices
#' @param A_List List of anisotropy matrices
#' @param coords Matrix of input coordinates (covariates)
#' 
#' @return A list of ScaleMat and DistMat.Mat matrices
#' 
#' @export
CalcScaleDistMats <- function(A_List, coords) {
    .Call(`_GPFDA_CalcScaleDistMats`, A_List, coords)
}

CalcScaleDistMatsAsym <- function(A_List, Astar_List, coords, coordsStar) {
    .Call(`_GPFDA_CalcScaleDistMatsAsym`, A_List, Astar_List, coords, coordsStar)
}

CovMaternCpp <- function(input, inputNew, cc, A, nu) {
    .Call(`_GPFDA_CovMaternCpp`, input, inputNew, cc, A, nu)
}

CovMaternCpp_sq <- function(input, cc, A, nu) {
    .Call(`_GPFDA_CovMaternCpp_sq`, input, cc, A, nu)
}

#' @title Calculate generalised distances
#' @description Calculates the generalised distance between vectors t and t'
#' using an anisotropy matrix A.
#' 
#' \itemize{
#' \item \code{DistMat} and \code{DistMat_sq} calculate:
#' \deqn{ [(t - t')^{p/2}]^T A  (t - t')^{p/2}  }
#' \item \code{DistMatLinear} and \code{DistMatLinear_sq} calculate:
#' \deqn{ t^T A t' }
#' }
#' 
#' 
#' @name DistanceMatrix
#' @param input Vector of the input coordinate t
#' @param inputNew Vector of the input coordinate t'
#' @param A Anisotropy matrix A
#' @param power Power value p
#' @details The \code{DistMat_sq} and \code{DistMatLinear_sq} functions are 
#' used when input vectors t and t' are identical, returning a symmetric matrix. \cr \cr
#' When \code{DistMat} and \code{DistMat_sq} functions are used in 
#' powered exponential kernels, power=1 gives the exponential kernel and 
#' power=2 gives the squared exponential one. \cr \cr
#' \code{DistMatLinear} and \code{DistMatLinear_sq} functions are used in the 
#' linear covariance kernel.
#' @return A matrix
NULL

#' @rdname DistanceMatrix
#' @export
DistMat <- function(input, inputNew, A, power) {
    .Call(`_GPFDA_DistMat`, input, inputNew, A, power)
}

#' @rdname DistanceMatrix
#' @export
DistMat_sq <- function(input, A, power) {
    .Call(`_GPFDA_DistMat_sq`, input, A, power)
}

#' @rdname DistanceMatrix
#' @export
DistMatLinear <- function(input, inputNew, A) {
    .Call(`_GPFDA_DistMatLinear`, input, inputNew, A)
}

#' @rdname DistanceMatrix
#' @export
DistMatLinear_sq <- function(input, A) {
    .Call(`_GPFDA_DistMatLinear_sq`, input, A)
}

KCGP <- function(X, idx, va0s, va1s, A0s, A1s, sig) {
    .Call(`_GPFDA_KCGP`, X, idx, va0s, va1s, A0s, A1s, sig)
}

KCGPnm <- function(X, Xp, idx, idx_new, va0s, va1s, A0s, A1s, sig) {
    .Call(`_GPFDA_KCGPnm`, X, Xp, idx, idx_new, va0s, va1s, A0s, A1s, sig)
}

