# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CalcScaleDistMats <- function(A_List, coords) {
    .Call('_GPFDA_CalcScaleDistMats', PACKAGE = 'GPFDA', A_List, coords)
}

CalcScaleDistMatsAsym <- function(A_List, Astar_List, coords, coordsStar) {
    .Call('_GPFDA_CalcScaleDistMatsAsym', PACKAGE = 'GPFDA', A_List, Astar_List, coords, coordsStar)
}

CovMaternCpp <- function(X, Xnew, cc, A, nu) {
    .Call('_GPFDA_CovMaternCpp', PACKAGE = 'GPFDA', X, Xnew, cc, A, nu)
}

CovMaternCpp_sq <- function(X, cc, A, nu) {
    .Call('_GPFDA_CovMaternCpp_sq', PACKAGE = 'GPFDA', X, cc, A, nu)
}

DistMat <- function(X, Xnew, A, power) {
    .Call('_GPFDA_DistMat', PACKAGE = 'GPFDA', X, Xnew, A, power)
}

DistMatLinear <- function(X, Xnew, A) {
    .Call('_GPFDA_DistMatLinear', PACKAGE = 'GPFDA', X, Xnew, A)
}

DistMatLinear_sq <- function(X, A) {
    .Call('_GPFDA_DistMatLinear_sq', PACKAGE = 'GPFDA', X, A)
}

DistMat_sq <- function(X, A, power) {
    .Call('_GPFDA_DistMat_sq', PACKAGE = 'GPFDA', X, A, power)
}

KCGP <- function(X, idx, va0s, va1s, A0s, A1s, sig) {
    .Call('_GPFDA_KCGP', PACKAGE = 'GPFDA', X, idx, va0s, va1s, A0s, A1s, sig)
}

KCGPnm <- function(X, Xp, idx, idx_new, va0s, va1s, A0s, A1s, sig) {
    .Call('_GPFDA_KCGPnm', PACKAGE = 'GPFDA', X, Xp, idx, idx_new, va0s, va1s, A0s, A1s, sig)
}

