// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// calcScaleDistMats
List calcScaleDistMats(List A_List, NumericMatrix coords);
RcppExport SEXP _GPFDA_calcScaleDistMats(SEXP A_ListSEXP, SEXP coordsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type A_List(A_ListSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type coords(coordsSEXP);
    rcpp_result_gen = Rcpp::wrap(calcScaleDistMats(A_List, coords));
    return rcpp_result_gen;
END_RCPP
}
// calcScaleDistMatsAsym
List calcScaleDistMatsAsym(List A_List, List Astar_List, NumericMatrix coords, NumericMatrix coordsStar);
RcppExport SEXP _GPFDA_calcScaleDistMatsAsym(SEXP A_ListSEXP, SEXP Astar_ListSEXP, SEXP coordsSEXP, SEXP coordsStarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type A_List(A_ListSEXP);
    Rcpp::traits::input_parameter< List >::type Astar_List(Astar_ListSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type coordsStar(coordsStarSEXP);
    rcpp_result_gen = Rcpp::wrap(calcScaleDistMatsAsym(A_List, Astar_List, coords, coordsStar));
    return rcpp_result_gen;
END_RCPP
}
// CovMaternCpp
arma::mat CovMaternCpp(NumericMatrix input, NumericMatrix inputNew, NumericVector cc, NumericMatrix A, NumericVector nu);
RcppExport SEXP _GPFDA_CovMaternCpp(SEXP inputSEXP, SEXP inputNewSEXP, SEXP ccSEXP, SEXP ASEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type input(inputSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type inputNew(inputNewSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cc(ccSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(CovMaternCpp(input, inputNew, cc, A, nu));
    return rcpp_result_gen;
END_RCPP
}
// CovMaternCppSq
arma::mat CovMaternCppSq(NumericMatrix input, NumericVector cc, NumericMatrix A, NumericVector nu);
RcppExport SEXP _GPFDA_CovMaternCppSq(SEXP inputSEXP, SEXP ccSEXP, SEXP ASEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type input(inputSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cc(ccSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(CovMaternCppSq(input, cc, A, nu));
    return rcpp_result_gen;
END_RCPP
}
// distMat
arma::mat distMat(NumericMatrix input, NumericMatrix inputNew, NumericMatrix A, NumericVector power);
RcppExport SEXP _GPFDA_distMat(SEXP inputSEXP, SEXP inputNewSEXP, SEXP ASEXP, SEXP powerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type input(inputSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type inputNew(inputNewSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type power(powerSEXP);
    rcpp_result_gen = Rcpp::wrap(distMat(input, inputNew, A, power));
    return rcpp_result_gen;
END_RCPP
}
// distMatSq
arma::mat distMatSq(NumericMatrix input, NumericMatrix A, NumericVector power);
RcppExport SEXP _GPFDA_distMatSq(SEXP inputSEXP, SEXP ASEXP, SEXP powerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type input(inputSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type power(powerSEXP);
    rcpp_result_gen = Rcpp::wrap(distMatSq(input, A, power));
    return rcpp_result_gen;
END_RCPP
}
// distMatLinear
arma::mat distMatLinear(NumericMatrix input, NumericMatrix inputNew, NumericMatrix A);
RcppExport SEXP _GPFDA_distMatLinear(SEXP inputSEXP, SEXP inputNewSEXP, SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type input(inputSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type inputNew(inputNewSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(distMatLinear(input, inputNew, A));
    return rcpp_result_gen;
END_RCPP
}
// distMatLinearSq
arma::mat distMatLinearSq(NumericMatrix input, NumericMatrix A);
RcppExport SEXP _GPFDA_distMatLinearSq(SEXP inputSEXP, SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type input(inputSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(distMatLinearSq(input, A));
    return rcpp_result_gen;
END_RCPP
}
// KCGP
arma::mat KCGP(NumericMatrix X, NumericVector idx, NumericVector va0s, NumericVector va1s, List A0s, List A1s, NumericVector sig);
RcppExport SEXP _GPFDA_KCGP(SEXP XSEXP, SEXP idxSEXP, SEXP va0sSEXP, SEXP va1sSEXP, SEXP A0sSEXP, SEXP A1sSEXP, SEXP sigSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type va0s(va0sSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type va1s(va1sSEXP);
    Rcpp::traits::input_parameter< List >::type A0s(A0sSEXP);
    Rcpp::traits::input_parameter< List >::type A1s(A1sSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sig(sigSEXP);
    rcpp_result_gen = Rcpp::wrap(KCGP(X, idx, va0s, va1s, A0s, A1s, sig));
    return rcpp_result_gen;
END_RCPP
}
// KCGPnm
arma::mat KCGPnm(NumericMatrix X, NumericMatrix Xp, NumericVector idx, NumericVector idx_new, NumericVector va0s, NumericVector va1s, List A0s, List A1s, NumericVector sig);
RcppExport SEXP _GPFDA_KCGPnm(SEXP XSEXP, SEXP XpSEXP, SEXP idxSEXP, SEXP idx_newSEXP, SEXP va0sSEXP, SEXP va1sSEXP, SEXP A0sSEXP, SEXP A1sSEXP, SEXP sigSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Xp(XpSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type idx_new(idx_newSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type va0s(va0sSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type va1s(va1sSEXP);
    Rcpp::traits::input_parameter< List >::type A0s(A0sSEXP);
    Rcpp::traits::input_parameter< List >::type A1s(A1sSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sig(sigSEXP);
    rcpp_result_gen = Rcpp::wrap(KCGPnm(X, Xp, idx, idx_new, va0s, va1s, A0s, A1s, sig));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GPFDA_calcScaleDistMats", (DL_FUNC) &_GPFDA_calcScaleDistMats, 2},
    {"_GPFDA_calcScaleDistMatsAsym", (DL_FUNC) &_GPFDA_calcScaleDistMatsAsym, 4},
    {"_GPFDA_CovMaternCpp", (DL_FUNC) &_GPFDA_CovMaternCpp, 5},
    {"_GPFDA_CovMaternCppSq", (DL_FUNC) &_GPFDA_CovMaternCppSq, 4},
    {"_GPFDA_distMat", (DL_FUNC) &_GPFDA_distMat, 4},
    {"_GPFDA_distMatSq", (DL_FUNC) &_GPFDA_distMatSq, 3},
    {"_GPFDA_distMatLinear", (DL_FUNC) &_GPFDA_distMatLinear, 3},
    {"_GPFDA_distMatLinearSq", (DL_FUNC) &_GPFDA_distMatLinearSq, 2},
    {"_GPFDA_KCGP", (DL_FUNC) &_GPFDA_KCGP, 7},
    {"_GPFDA_KCGPnm", (DL_FUNC) &_GPFDA_KCGPnm, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_GPFDA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
